# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89837ad5f359e5dc2198227f863f9fc2"
application_url = "https://reports-late-heater-modifications.trycloudflare.com"
embedded = true
name = "Product Label Generator"
handle = "product-label-generator-3"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reports-late-heater-modifications.trycloudflare.com/auth/callback",
  "https://reports-late-heater-modifications.trycloudflare.com/auth/shopify/callback",
  "https://reports-late-heater-modifications.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "quickstart-e17ebecc.myshopify.com"
automatically_update_urls_on_dev = true
