name = "product-labels"
type = "theme"
extension_points = [
  "product.description.position",
  "section.product-template.product-details"
]

[[metafields]]
namespace = "custom"
key = "product_labels"
type = "json"

[capabilities]
api_access = true
block_progress = true
network_access = true

[settings]
fields = []

